language: python
python:
- 2.7
- 3.6
before_script:
- wget http://times.cs.uiuc.edu/~wang296/Data/LARA/TripAdvisor/TripAdvisorJson.tar.bz2
script:
- python setup.py test
deploy:
  provider: pypi
  user: jkawamoto
  password:
    secure: BYWwrrmR3zMgpzx+w/BOneSVgUPI258USkcSk/qdnLHjjM6VfnZWA6sp/f+IKeNFvy/qUE+jpGxH51QgwWK3c8JShlve21NUhek0Z6np+hGt43mIhiqcCubBw4hET1uSH6s9GjutIq7A5zt4ewxXEm0ria5MYLXmlEKK7YjOpS9l8yW7bS4lGEPPsclrDlAy+x2RjJzvaoBRsiF1Uvo82k57I7DPujoz7drFz1j/uxi9dUEyE9cibkacOJWI8DGfAL+r2/ftQsKD0Z6MErb5GO6bG6wze6EvZ4FvAbG5V7PQEgmXJWAzvzP3FOzXfS+IgpC96oL18TygAGE7OiQ2zIH86dkQ1jiTglz/Wu3mhYi++PGyIqa/pmrcF4k0iXkTBrNe/6tMqzWomj5VZSylHuPMfs9QqrrykDc2F903leiqYQ+NofwE+A5L45auwxggZSFDolEF0OE12UCd4l7oXDXkjtpfRtFJcrv1RIJbY6h016sFyuaODghR36u/qmtmSZhI4HLzXVPiELYb6C6PUQhqLyH4oRl5TkDZ/fKzFXFB4eEPYMRch1b2lOnS2XDgYJ3TZ1NLgS0Ls1ycrQ7gv9c5yMAVSzjTIwLGgHZMmp0weDGJ0HcRkGKmxByEB2vZVqOnfSzAxDTchODt1eD61uwEglVYRxRKbaKuh3yS9lI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rgmining/tripadvisor
