__version__ = "0.1.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.1.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8f8ad8608f45a0cb1e2ce281a9d1cd77fa396d72'
__git_head_subject__ = u'Finished Release v0.1.7'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-07-09 15:25:13'
