__version__ = "0.4.38"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.4.38)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8d4deb0d70cb5f2ed506057cd3aa4da59add0ab1'
__git_head_subject__ = u'Finished Release v0.4.38'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-07-09 15:09:52'
