language: python
sudo: false

matrix:
    include:
        # pyXX-plone_sunburst,pyXX-plone_barceloneta
        - python: "2.7"
          env: TOXENV=py27-plone_org_4,py27-plone_org_5,py27-plone_classic
        - python: "3.4"
          env: TOXENV=py34-plone_org_4,py34-plone_org_5,py34-plone_classic
        - python: "3.5"
          env: TOXENV=py35-plone_org_4,py35-plone_org_5,py35-plone_classic
        - python: "3.6"
          env: TOXENV=py36-plone_org_4,py36-plone_org_5,py36-plone_classic,isort,flake8
        - python: "pypy"
          env: TOXENV=pypy-plone_org_4,pypy-plone_org_5,pypy-plone_classic

install:
    - travis_retry pip install tox coveralls coverage

script:
    - travis_retry tox

cache:
    directory:
        - $HOME/.cache/pip

notifications:
    email: false
