from ....tl.mtproto_request import MTProtoRequest


class GetConfigRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    help.getConfig#c4f9186b  = Config"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xc4f9186b
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xd3262a4a

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(GetConfigRequest.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return GetConfigRequest()

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'help.getConfig#c4f9186b  = Config'

    def __str__(self):
        return '(help.getConfig (ID: 0xc4f9186b) = ())'.format()
