__version__ = "0.1.14"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.1.14)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'b08b1ac9b4eea05ceaf60d13db5433b7d767d4e8'
__git_head_subject__ = u'Finished Release v0.1.14'
__git_head_message__ = u''
__git_dirty_diff__ = u''