# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_thumb_id',
            field=models.CharField(default='home_slider', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='use_simple_settings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_slider_slide', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_slider_slider', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
