# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrogant', '0003_auto_20170707_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brand',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='地址',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
