__version__ = "0.2.4"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.2.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '42ef9f17c337201f20c518fed3295e3b5d188049'
__git_head_subject__ = u'Finished Release v0.2.4'
__git_head_message__ = u''
__git_dirty_diff__ = u''