
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-27T16:55:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aeac7bc20653ddea07684c836d749a03533e77bf",
 "version": "v0.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
