sudo: required
language: python
python:
  - 2.7
  - 3.6
addons:
  firefox: 53.0
env:
  global:
    - DISPLAY=:99.0
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36
  exclude:
    - python: 2.7
    - python: 3.6
before_install:
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - gunzip -c geckodriver.tar.gz | tar xopf -
  - chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
  - firefox --version
  - geckodriver --version
install:
  - pip install tox
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - tox
notifications:
  email: fte-ci@mozilla.com
deploy:
  provider: pypi
  user: davehunt
  password:
    secure: GyTB/x+/F1DNmAWF4K8keaBgwUTq6AVgCfdMzArPSLiHxs4Fi98Y44U6YM4fy5qwZ8oJxYYwdlWoooStIYouV8PEg0GOl+x1m7eb02XXZEufVUqQ4p5sN3HHeUmj2Et0j0o0AkUvAZjY2zCS3hI9U8wH+rLrkyR/1g8a88HLeHo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: mozilla/fxapom
    python: 2.7
    condition: "$TOXENV = py27"
