
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-12T13:44:14+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "b071c44572f79ab74fa5bb719194fedacf1603c5",
 "version": "0+untagged.83.gb071c44.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
