# coding: utf-8

"""
    OrderCloud

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: ordercloud@four51.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.access_token import AccessToken
from .models.address import Address
from .models.address_assignment import AddressAssignment
from .models.approval_rule import ApprovalRule
from .models.base_spec import BaseSpec
from .models.buyer import Buyer
from .models.buyer_address import BuyerAddress
from .models.buyer_credit_card import BuyerCreditCard
from .models.buyer_product import BuyerProduct
from .models.buyer_shipment import BuyerShipment
from .models.buyer_spec import BuyerSpec
from .models.catalog import Catalog
from .models.catalog_assignment import CatalogAssignment
from .models.category import Category
from .models.category_assignment import CategoryAssignment
from .models.category_product_assignment import CategoryProductAssignment
from .models.cost_center import CostCenter
from .models.cost_center_assignment import CostCenterAssignment
from .models.credit_card import CreditCard
from .models.credit_card_assignment import CreditCardAssignment
from .models.impersonate_token_request import ImpersonateTokenRequest
from .models.impersonation_config import ImpersonationConfig
from .models.inventory import Inventory
from .models.line_item import LineItem
from .models.line_item_product import LineItemProduct
from .models.line_item_spec import LineItemSpec
from .models.list_address import ListAddress
from .models.list_address_assignment import ListAddressAssignment
from .models.list_approval_rule import ListApprovalRule
from .models.list_args import ListArgs
from .models.list_buyer import ListBuyer
from .models.list_buyer_address import ListBuyerAddress
from .models.list_buyer_credit_card import ListBuyerCreditCard
from .models.list_buyer_product import ListBuyerProduct
from .models.list_buyer_shipment import ListBuyerShipment
from .models.list_buyer_spec import ListBuyerSpec
from .models.list_catalog import ListCatalog
from .models.list_catalog_assignment import ListCatalogAssignment
from .models.list_category import ListCategory
from .models.list_category_assignment import ListCategoryAssignment
from .models.list_category_product_assignment import ListCategoryProductAssignment
from .models.list_cost_center import ListCostCenter
from .models.list_cost_center_assignment import ListCostCenterAssignment
from .models.list_credit_card import ListCreditCard
from .models.list_credit_card_assignment import ListCreditCardAssignment
from .models.list_impersonation_config import ListImpersonationConfig
from .models.list_line_item import ListLineItem
from .models.list_message_cc_listener_assignment import ListMessageCCListenerAssignment
from .models.list_message_config import ListMessageConfig
from .models.list_message_sender import ListMessageSender
from .models.list_message_sender_assignment import ListMessageSenderAssignment
from .models.list_order import ListOrder
from .models.list_order_approval import ListOrderApproval
from .models.list_order_promotion import ListOrderPromotion
from .models.list_payment import ListPayment
from .models.list_price_schedule import ListPriceSchedule
from .models.list_product import ListProduct
from .models.list_product_assignment import ListProductAssignment
from .models.list_product_catalog_assignment import ListProductCatalogAssignment
from .models.list_promotion import ListPromotion
from .models.list_promotion_assignment import ListPromotionAssignment
from .models.list_security_profile import ListSecurityProfile
from .models.list_security_profile_assignment import ListSecurityProfileAssignment
from .models.list_shipment import ListShipment
from .models.list_shipment_item import ListShipmentItem
from .models.list_spec import ListSpec
from .models.list_spec_option import ListSpecOption
from .models.list_spec_product_assignment import ListSpecProductAssignment
from .models.list_spending_account import ListSpendingAccount
from .models.list_spending_account_assignment import ListSpendingAccountAssignment
from .models.list_supplier import ListSupplier
from .models.list_user import ListUser
from .models.list_user_group import ListUserGroup
from .models.list_user_group_assignment import ListUserGroupAssignment
from .models.list_variant import ListVariant
from .models.me_buyer import MeBuyer
from .models.me_user import MeUser
from .models.message_cc_listener_assignment import MessageCCListenerAssignment
from .models.message_config import MessageConfig
from .models.message_sender import MessageSender
from .models.message_sender_assignment import MessageSenderAssignment
from .models.meta import Meta
from .models.order import Order
from .models.order_approval import OrderApproval
from .models.order_approval_info import OrderApprovalInfo
from .models.order_promotion import OrderPromotion
from .models.password_reset import PasswordReset
from .models.password_reset_request import PasswordResetRequest
from .models.payment import Payment
from .models.payment_transaction import PaymentTransaction
from .models.price_break import PriceBreak
from .models.price_schedule import PriceSchedule
from .models.product import Product
from .models.product_assignment import ProductAssignment
from .models.product_base import ProductBase
from .models.product_catalog_assignment import ProductCatalogAssignment
from .models.promotion import Promotion
from .models.promotion_assignment import PromotionAssignment
from .models.security_profile import SecurityProfile
from .models.security_profile_assignment import SecurityProfileAssignment
from .models.shipment import Shipment
from .models.shipment_item import ShipmentItem
from .models.spec import Spec
from .models.spec_option import SpecOption
from .models.spec_product_assignment import SpecProductAssignment
from .models.spending_account import SpendingAccount
from .models.spending_account_assignment import SpendingAccountAssignment
from .models.supplier import Supplier
from .models.token_password_reset import TokenPasswordReset
from .models.user import User
from .models.user_group import UserGroup
from .models.user_group_assignment import UserGroupAssignment
from .models.variant import Variant

# import apis into sdk package
from .apis.address_api import AddressApi
AddressApi = AddressApi()
from .apis.admin_address_api import AdminAddressApi
AdminAddressApi = AdminAddressApi()
from .apis.admin_user_api import AdminUserApi
AdminUserApi = AdminUserApi()
from .apis.admin_user_group_api import AdminUserGroupApi
AdminUserGroupApi = AdminUserGroupApi()
from .apis.approval_rule_api import ApprovalRuleApi
ApprovalRuleApi = ApprovalRuleApi()
from .apis.buyer_api import BuyerApi
BuyerApi = BuyerApi()
from .apis.catalog_api import CatalogApi
CatalogApi = CatalogApi()
from .apis.category_api import CategoryApi
CategoryApi = CategoryApi()
from .apis.cost_center_api import CostCenterApi
CostCenterApi = CostCenterApi()
from .apis.credit_card_api import CreditCardApi
CreditCardApi = CreditCardApi()
from .apis.impersonation_config_api import ImpersonationConfigApi
ImpersonationConfigApi = ImpersonationConfigApi()
from .apis.line_item_api import LineItemApi
LineItemApi = LineItemApi()
from .apis.me_api import MeApi
MeApi = MeApi()
from .apis.message_senders_api import MessageSendersApi
MessageSendersApi = MessageSendersApi()
from .apis.order_api import OrderApi
OrderApi = OrderApi()
from .apis.password_reset_api import PasswordResetApi
PasswordResetApi = PasswordResetApi()
from .apis.payment_api import PaymentApi
PaymentApi = PaymentApi()
from .apis.price_schedule_api import PriceScheduleApi
PriceScheduleApi = PriceScheduleApi()
from .apis.product_api import ProductApi
ProductApi = ProductApi()
from .apis.promotion_api import PromotionApi
PromotionApi = PromotionApi()
from .apis.security_profile_api import SecurityProfileApi
SecurityProfileApi = SecurityProfileApi()
from .apis.shipment_api import ShipmentApi
ShipmentApi = ShipmentApi()
from .apis.spec_api import SpecApi
SpecApi = SpecApi()
from .apis.spending_account_api import SpendingAccountApi
SpendingAccountApi = SpendingAccountApi()
from .apis.supplier_api import SupplierApi
SupplierApi = SupplierApi()
from .apis.supplier_user_api import SupplierUserApi
SupplierUserApi = SupplierUserApi()
from .apis.supplier_user_group_api import SupplierUserGroupApi
SupplierUserGroupApi = SupplierUserGroupApi()
from .apis.user_api import UserApi
UserApi = UserApi()
from .apis.user_group_api import UserGroupApi
UserGroupApi = UserGroupApi()

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()

#import the auth class
from .apis.auth_api import Auth
from .apis.auth_api import Impersonation
auth = Auth()
impersonation = Impersonation()
