# HDX configuration
hdx_prod_site:
  url: "https://data.humdata.org/"
  username: ~
  password: ~
hdx_demo_site:
  url: "https://demo-data.humdata.org/"
  username: "ZGVtbzE3OQ=="
  password: "ZnVud2l0aGhkeA=="
hdx_test_site:
  url: "https://test-data.humdata.org/"
  username: "ZGF0YXByb2plY3Q="
  password: "aHVtZGF0YQ=="
hdx_feature_site:
  url: "https://feature-data.humdata.org/"
  username: "ZGF0YXByb2plY3Q="
  password: "aHVtZGF0YQ=="
dataset:
  required_fields:
    - name
    - private
    - title
    - notes
    - dataset_source
    - owner_org
    - dataset_date
    - groups
    - license_id
    - methodology
    - data_update_frequency
resource:
  dataset_id: package_id
  required_fields:
    - package_id
    - name
    - format
    - url
    - description
    - url_type
    - resource_type
galleryitem:
  dataset_id: dataset_id
  required_fields:
    - dataset_id
    - title
    - type
    - description
    - url
    - image_url
  ignore_on_update: dataset_id
user:
  required_fields:
    - name
    - email
    - password
    - fullname
    - about
  ignore_on_update: password
organization:
  required_fields:
    - name
    - title
    - description
