from ...tl.mtproto_request import MTProtoRequest


class InputUserSelf(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    inputUserSelf#f7c1b13f  = InputUser"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xf7c1b13f
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0xe669bf46

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(InputUserSelf.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return InputUserSelf()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputUserSelf#f7c1b13f  = InputUser'

    def __str__(self):
        return '(inputUserSelf (ID: 0xf7c1b13f) = ())'.format()
