language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOX_ENV=py27-flake8
    - python: 2.7
      env: TOX_ENV=py27-django1.8-drf3.6
    - python: 2.7
      env: TOX_ENV=py27-django1.10-drf3.6
    - python: 2.7
      env: TOX_ENV=py27-django1.11-drf3.6
    - python: 3.4
      env: TOX_ENV=py34-django1.8-drf3.6
    - python: 3.4
      env: TOX_ENV=py34-django1.10-drf3.6
    - python: 3.4
      env: TOX_ENV=py34-django1.11-drf3.6
    - python: 3.5
      env: TOX_ENV=py35-django1.8-drf3.6
    - python: 3.5
      env: TOX_ENV=py35-django1.10-drf3.6
    - python: 3.5
      env: TOX_ENV=py35-django1.11-drf3.6
    - python: 3.6
      env: TOX_ENV=py36-django1.8-drf3.6
    - python: 3.6
      env: TOX_ENV=py36-django1.10-drf3.6
    - python: 3.6
      env: TOX_ENV=py36-django1.11-drf3.6

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

branches:
  only:
    - master
