environment:

  matrix:

    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:

  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:

  - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%:%APPVEYOR_BUILD_FOLDER%\tests
  - "%PYTHON%\\python.exe -m pytest -v tests"
