__version__ = "0.3.15"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.3.15)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '2af19a025102206202d5d18aa0c84cd407943782'
__git_head_subject__ = u'Finished Release v0.3.15'
__git_head_message__ = u''
__git_dirty_diff__ = u''