from enum import Enum


class TransactionStatuses(Enum):
    INITIALIZING = "INITIALIZING"
    INITIATED = "INITIATED"
    PROCESSED = "PROCESSED"
    PENDING = "PENDING"
    CALLBACK_WAITING = "CALLBACK_WAITING"
    PENDING_REFUND = "PENDING_REFUND"
    REFUNDED = "REFUNDED"
    TIMEOUT = "TIMEOUT"
    BOUNCED = "BOUNCED"
    FROZEN = "FROZEN"
    FAILED = "FAILED"
    ABORTED = "ABORTED"
