
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-10T16:34:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcfcf2952ecd14c8360e19b4c1984a580d9d774d",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
