
'''
This file is automatically generated by setup.py, So don't edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.12.2.post1',
    'branch_nick': '(detached',
    'revision_id': '7a3589140983537bcbb11e1cf481db914c3ba985',
    'revno': 5202
}
