
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b97294d3ddf0786aa0db9e2478503d9671ef5fb3",
 "version": "1.0.0.post.dev572"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
