# coding: utf-8
# Generated by setup.py for PyCBC on 2017-07-13 18:21:34 +0000.

version = '1.7.5'
date = '2017-07-13 16:59:03 +0000'
release = True
last_release = '1.7.5'

git_hash = 'c52b16863162a73023f6d3f094e89555938e16d8'
git_branch = 'None'
git_tag = 'v1.7.5'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'travis@localhost <travis@localhost>'
git_build_date = '2017-07-13 18:21:34 +0000'
git_verbose_msg = """Branch: None
Tag: v1.7.5
Id: c52b16863162a73023f6d3f094e89555938e16d8
Builder: travis@localhost <travis@localhost>
Build date: 2017-07-13 18:21:34 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
