
# This file was generated by 'versioneer.py' from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4dev4'
version_full = '58e1ca40f0b904442ae8e275db7915b27108ccf6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

