
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-05T07:01:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "61d2c93dc5ded5d71ffea30a91deb66dc33cc0ae",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
