# Control file for Travis CI (http://travis-ci.org)
# Must be located in the root directory of the Git repository.

# By default, notification emails are sent to the PR creator and commiter.
notifications:
  email: false

# We define the job matrix explicitly, in order to minimize the
# combinations.
# For OS-X, using an explicit matrix is required, because Travis at
# this point only has half-baked support for Python on OS-X that does
# not work. Also, on OS-X, it needs to be invoked with language=generic
# and an empty 'python' variable in order to prevent that Travis attempts
# to install Python.
# TODO: Figure out how specific versions of Python 3.x can be used with OS-X
matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: "2.7"
      env:
        - PACKAGE_LEVEL=minimum
    - os: linux
      sudo: required
      language: python
      python: "2.7"
      env:
        - PACKAGE_LEVEL=latest
    - os: linux
      sudo: required
      language: python
      python: "3.4"
      env:
        - PACKAGE_LEVEL=minimum
#    - os: linux
#      sudo: required
#      language: python
#      python: "3.5"
#      env:
#        - PACKAGE_LEVEL=minimum
    - os: linux
      sudo: required
      language: python
      python: "3.6"
      env:
        - PACKAGE_LEVEL=latest
#    - os: linux
#      sudo: required
#      language: python
#      python: "pypy-5.3.1"  # Python 2.7.10
#      env:
#        - PACKAGE_LEVEL=minimum
    - os: osx
      sudo: required
      language: generic
      python:
      env:
        - PACKAGE_LEVEL=minimum
        - PYTHON=2
#    - os: osx
#      sudo: required
#      language: generic
#      python:
#      env:
#        - PACKAGE_LEVEL=latest
#        - PYTHON=2
#    - os: osx
#      sudo: required
#      language: generic
#      python:
#      env:
#        - PACKAGE_LEVEL=minimum
#        - PYTHON=3
    - os: osx
      sudo: required
      language: generic
      python:
      env:
        - PACKAGE_LEVEL=latest
        - PYTHON=3

# commands to install dependencies
install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      if [[ ${PYTHON:0:1} == '2' ]]; then
        OSX_PYTHON_PKG=python;
        export PYTHON_CMD=python;
        export PIP_CMD=pip;
      else
        OSX_PYTHON_PKG=python3;
        export PYTHON_CMD=python3;
        export PIP_CMD=pip3;
      fi;
      brew update;
      brew ls --versions $OSX_PYTHON_PKG && brew upgrade $OSX_PYTHON_PKG || brew install $OSX_PYTHON_PKG;
    else
      export PYTHON_CMD=python;
      export PIP_CMD=pip;
    fi
  - $PIP_CMD list
  - make install
  - $PIP_CMD list
  - make develop
  - $PIP_CMD install python-coveralls
  - $PIP_CMD list
  - make pyshow
  - bash -c "echo $TRAVIS_EVENT_TYPE"

# commands to run builds & tests
script:
  - make check
  - make test
  - if [[ $TRAVIS_EVENT_TYPE == 'cron' ]]; then
      make build;
      make builddoc;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 && $PACKAGE_LEVEL == latest ]]; then coveralls; fi
