# Autogenerated by Astropy's setup.py on 2017-06-15 16:33:48.721077
from __future__ import unicode_literals
import datetime

version = "1.3.3"
githash = "7c6752495d1320efc7b1994e15cbcccd6e6d0b16"


major = 1
minor = 3
bugfix = 3

release = True
timestamp = datetime.datetime(2017, 6, 15, 16, 33, 48, 721077)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
