__version__ = "0.5.1"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.5.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e8efc3d2213315fcbeb9d1cc3f10fde7eb219d24'
__git_head_subject__ = u'Finished Release v0.5.1'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-07-09 15:18:09'
