
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bdb5f0273713fbd980c39bb73726d8d64ec4b547",
 "version": "0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
