sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: FOO=1

  include:
    - python: '2.7'
      env: FOO=2


cache:
  pip: true
  directories:
  - $HOME/capnp

  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - python-dev

install:
  - pip install -U pip # so that we can use wheels
  - pip install cython>=0.25

script:
  - python setup.py build_ext --inplace
  - py.test
