# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='guzzle.proto',
  package='openhtf',
  serialized_pb='\n\x0cguzzle.proto\x12\x07openhtf\"N\n\x0fTestRunEnvelope\x12*\n\x0cpayload_type\x18\x02 \x01(\x0e\x32\x14.openhtf.PayloadType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c*S\n\x0bPayloadType\x12\x17\n\x13\x43OMPRESSED_TEST_RUN\x10\x01\x12\x13\n\x0f\x43OMPRESSED_VARZ\x10\x02\x12\x16\n\x12\x43OMPRESSED_LOGFILE\x10\x03')

_PAYLOADTYPE = descriptor.EnumDescriptor(
  name='PayloadType',
  full_name='openhtf.PayloadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMPRESSED_TEST_RUN', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COMPRESSED_VARZ', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COMPRESSED_LOGFILE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=105,
  serialized_end=188,
)


COMPRESSED_TEST_RUN = 1
COMPRESSED_VARZ = 2
COMPRESSED_LOGFILE = 3



_TESTRUNENVELOPE = descriptor.Descriptor(
  name='TestRunEnvelope',
  full_name='openhtf.TestRunEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='payload_type', full_name='openhtf.TestRunEnvelope.payload_type', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='openhtf.TestRunEnvelope.payload', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=103,
)

_TESTRUNENVELOPE.fields_by_name['payload_type'].enum_type = _PAYLOADTYPE
DESCRIPTOR.message_types_by_name['TestRunEnvelope'] = _TESTRUNENVELOPE

class TestRunEnvelope(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTRUNENVELOPE
  
  # @@protoc_insertion_point(class_scope:openhtf.TestRunEnvelope)

# @@protoc_insertion_point(module_scope)
