from ....tl.mtproto_request import MTProtoRequest


class LeaveChannelRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    channels.leaveChannel#f836aa95 channel:InputChannel = Updates"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0xf836aa95
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0x8af52aac

    def __init__(self, channel):
        """
        :param channel: Telegram type: "InputChannel".

        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, UpdatesTg, UpdateShortSentMessage.
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default

        self.channel = channel

    def to_dict(self):
        return {
            'channel': None if self.channel is None else self.channel.to_dict(),
        }

    def on_send(self, writer):
        writer.write_int(LeaveChannelRequest.constructor_id, signed=False)
        self.channel.on_send(writer)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return LeaveChannelRequest(None)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'channels.leaveChannel#f836aa95 channel:InputChannel = Updates'

    def __str__(self):
        return '(channels.leaveChannel (ID: 0xf836aa95) = (channel={}))'.format(str(self.channel))
