sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U setuptools pylint coverage pep8 pydocstyle "pip>=7.0" wheel

install:
  - pip install -e .

script:
  - pep8 libagent
  - pylint --reports=no --rcfile .pylintrc libagent
  - pydocstyle libagent
  - coverage run --source libagent/ -m py.test -v

after_success:
  - coverage report

