language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to run tests, e.g. python setup.py test
install: 
  - pip install virtualenv
  - pip install codecov
script: 
  - make env
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then make pylint; fi
after_success:
  - codecov
after_failure:
- .env/bin/pip freeze

before_deploy:
  - python setup.py bdist_wheel

deploy:
  - provider: pypi
    user: vmalloc
    password:
      secure: EBE30QsQvwodsakJRtXvmeah0KRQoMpHQSfSACjE0FviWU6eHhgE7nSzxrTSwetmLaB/+hexkys8ULsE4Dxwgvd8aXJ5T6+GnhFkWLgaTl8Q39g/cnLqnVj+OCS95XlyFcWyBLsdyPY+tAc34YpYRfjuWgXup5UNc7Ze2KQ7wqk=
    on:
      tags: true
      repo: getslash/slash
  - provider: releases
    api_key:
      secure: LVS3CMERZiq7NjQNdteAwcq1ZOEWyu+KSaf80YFiMlkoSy9dh9UyxdZ99LSWvSvbeOOl+NX8zL+u5y61s/qDMJbEfbUVlkbhunYm3gZjZMTusfno19QoLEB4k2sYPFFnKyzB2ib6gHjJ7TVic4LQhK9jrUffEMljaAz5Fh7N5ww=
    file: build/bdist.*
    on:
      tags: true
      repo: getslash/slash
