
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-17T15:16:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef2528b7fea642dc858158aac0b0b261e6d59ff7",
 "version": "v0.1.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
