# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import logicmonitor
from logicmonitor.rest import ApiException
from logicmonitor.models.rest_ops_note_group_device_service_all_scope import RestOpsNoteGroupDeviceServiceAllScope


class TestRestOpsNoteGroupDeviceServiceAllScope(unittest.TestCase):
    """ RestOpsNoteGroupDeviceServiceAllScope unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRestOpsNoteGroupDeviceServiceAllScope(self):
        """
        Test RestOpsNoteGroupDeviceServiceAllScope
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = logicmonitor.models.rest_ops_note_group_device_service_all_scope.RestOpsNoteGroupDeviceServiceAllScope()
        pass


if __name__ == '__main__':
    unittest.main()
