language: python

# needed to use trusty
sudo: required

dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - python setup.py install

script:
  - coverage run --source=twstock setup.py test

after_success:
  - coveralls
  - codecov
