
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-18T18:07:21-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fcef20844779d0933e7f01bd730dd8b5fc15283",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
