
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bb39c6e146501a3090ad40dda7b1891dab7facad",
 "version": "0.1.0a55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
