
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-20T22:35:32+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "e02ebcd4a95f9baf05d75e97fa13f423016448ba",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
