language: python
cache:
  - pip
python:
    - 3.5
    - 3.6
before_install:
  - pip install -U pip
install:
    # The install requirements in travis virtualenv that will be cached
  - pip install tox-travis .[test]
script: tox
