language: python
python:
- 2.7
- 3.6
before_script:
- wget http://times.cs.uiuc.edu/~wang296/Data/LARA/Amazon/AmazonReviews.zip
script:
- python setup.py test
deploy:
  provider: pypi
  user: jkawamoto
  password:
    secure: ccWu1VxwU3Yr06euExUEb+KQPlreXUG0zTQN8iLliL9syiURHflyueoaPaflMm8BiJbcZe/RA5j9Z4GFQmNhqq6/itcSymAM0g5N740ym0cWtAiftfrWfWIB35Ke4Z3x4fsUU7d0qneczg+31eQjgbLMd4bf4BBnHWTZzmcfdasa5nvoRoHXMj+2TI2Zm4sRCyJdXemLFv/d+0b4OiJMSIQHB2jkN9BGKIjBJ2C1n8Ew+t1CHXS8MkpCDcNiPo9YQKK9jR/ZV1KHB7ibFVEJyiXJiXtAhR+TGj4v8AIGh4TXtyxPGt9K4PuyCoQ0FRZoDOngeyUwMl2Gx/5yLrsoT5l/soj82AMsEHLr8ERqBc3jPUSgTIuf5ijOJmHXMNHzxnf5AM457xwXVm/XcB7piGDB7PvZThlsR+yynLeEKJeQ30CqfR9C3ZI+273wr6TeWlqTRD62wxhD/iiJgbnXotI9a3EX2k1TPwWS4SsBkS0bOifJ/Sdh6lgk6Nbvm6jWaAokg3VyLHwqijsC1axiBrLuh4Yrz2PJSdPXpquL6ERp63Zv/vtsvdA3oEhLwvPbBTkYknotoAlh8jLUILo6wkyBpPv8T5RFgoz1jR6dPaP3NvQa9CGN5xrAyui4h57oVUE6DCJiyDoc+AzcgRusK5JlpB04DRbI2zgkOc/cS18=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rgmining/amazon
