# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2017-06-26 19:05:22.299287
from __future__ import unicode_literals
import datetime

version = "2.0rc1"
githash = "5abc0f82e640261f17646ae50be1546f9e3d8e8d"


major = 2
minor = 0
bugfix = 0

release = True
timestamp = datetime.datetime(2017, 6, 26, 19, 5, 22, 299287)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
