
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "731593b57082e675e0f661f6211f2dd261807561",
 "version": "0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
