__version__ = "0.2.13"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.2.13)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1ae7a59deb67efbe9f4ba4fd21114d0de03e4790'
__git_head_subject__ = u'Finished Release v0.2.13'
__git_head_message__ = u''
__git_dirty_diff__ = u''