# ============================================================================
# Config file for Quality Control
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_extension: "%(input_extension)s"
input_pattern: "%(input_pattern)s"
input_readtag: "%(input_readtag)"
input_samples: 
    file1: ""
    file2: ""

kraken:
    database_directory: toydb
