language: python
python:
- 2.7.13
- 3.6
addons:
  apt:
    packages:
    - gcc
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - python-numpy
    - python-scipy
    - python-sklearn
before_install:
- pip install -U pip scipy -v -v -v
script:
- python setup.py test
deploy:
  provider: pypi
  user: jkawamoto
  password:
    secure: NDt2J4x8+HZIHNFqzfYUQgth5Fab72TQH5Q93lMpLnW4j3g/cHcyovYrWgac+iDuFCfjZVlasFB8MMez7coO1YsncsFkEIO1k2elieOnHxcJZAnhlqPkuD8quOcb1ebtoRterjzR10Dopgqilg3620ij28SPCkYaUhP0HwImdW0saHnQAXm2IlZHzI3IVT4GmsNJJnklYfK/vP/FW/gcFTqKTl613phqsmuYza4GDaSiS2KcoQeDdJ4SDuNMgql34Tr05Ix2WTTaATLwSCYUqixZ+hIMB8UfHpzf8vNgG8X5n61B8P5+R5LJKrxeos6Ttfd4F2z4HQ3iIOpx+0AOkMD7L72YclP/b0SZseBEzlWbkvOQ8Ihn6hzn97q6xsIlepG2TKdRuSPrd+uVRBcmuQWAR3pFkhp+0D1csJ5oKSyzSxtLujNx5agHxpYOwGMR8MRqSGXTP7uih3SBnk0iqrtAXylP3OTdA2n7S6lOKUiclxE7xlolDBVCV/PU0uzkeYBn2qy51lxP1PbwBtLMxoAhzJIB/nuDOpFtIwJVfm3bXcpq1TVgKQS/8uewrVNnbXaGDIHz5A3dq1Z5bd2qHlV8mf6KWbOET9MSSU4RxZ+MlFh1LCnpVdNb0n7yH6QCeKTG/IMCM/u3aUD0YECIXtq1kqLWLUehTc93diYdKK0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rgmining/fraudar
