# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('RDBMS', 'RDBMS'), ('NoSql', 'NoSql'), ('Logger', 'Logger')], default='RDBMS', max_length=50)),
                ('cred_type', models.CharField(choices=[('POSTGRES', 'POSTGRES'), ('REDSHIFT', 'REDSHIFT'), ('ELASTICSEARCH', 'ELASTICSEARCH')], default='POSTGRES', max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=10)),
                ('db', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qvad_user_creds',
            },
        ),
    ]
