---
version: 1

# Uncomment the following line to preserve loggers defined before
# this configuration is applied.
#disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: WARN
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    # The filename specifies the log file, which defaults to /dev/null,
    # i.e. no file logging. The log file can be reset with the
    # logging.configure filename option.
    filename: /dev/null
    maxBytes: 10485760  # 10MB
    backupCount: 4
    encoding: utf8

root:
  # The root level can be reset by the logging.configure method level
  # option.
  level: INFO
  # The file handler can be added to the handlers by the
  # logging.configure method filename option.
  handlers: [console]
