# coding: utf-8

"""
    logicmonitor_sdk

    LogicMonitor is a cloud-based, full stack, IT infrastructure monitoring solution that allows you to manage your infrastructure from the cloud. logicmonitor_sdk lets you manage your LogicMonitor account programmatically.

    OpenAPI spec version: 1.0.0
    Contact: sdk@logicmonitor.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BigNumberInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'virtual_data_points': 'list[VirtualDataPoint]',
        'data_points': 'list[BigNumberDataPoint]',
        'big_number_items': 'list[BigNumberItem]'
    }

    attribute_map = {
        'virtual_data_points': 'virtualDataPoints',
        'data_points': 'dataPoints',
        'big_number_items': 'bigNumberItems'
    }

    def __init__(self, virtual_data_points=None, data_points=None, big_number_items=None):
        """
        BigNumberInfo - a model defined in Swagger
        """

        self._virtual_data_points = None
        self._data_points = None
        self._big_number_items = None
        self.discriminator = None

        if virtual_data_points is not None:
          self.virtual_data_points = virtual_data_points
        if data_points is not None:
          self.data_points = data_points
        self.big_number_items = big_number_items

    @property
    def virtual_data_points(self):
        """
        Gets the virtual_data_points of this BigNumberInfo.

        :return: The virtual_data_points of this BigNumberInfo.
        :rtype: list[VirtualDataPoint]
        """
        return self._virtual_data_points

    @virtual_data_points.setter
    def virtual_data_points(self, virtual_data_points):
        """
        Sets the virtual_data_points of this BigNumberInfo.

        :param virtual_data_points: The virtual_data_points of this BigNumberInfo.
        :type: list[VirtualDataPoint]
        """

        self._virtual_data_points = virtual_data_points

    @property
    def data_points(self):
        """
        Gets the data_points of this BigNumberInfo.

        :return: The data_points of this BigNumberInfo.
        :rtype: list[BigNumberDataPoint]
        """
        return self._data_points

    @data_points.setter
    def data_points(self, data_points):
        """
        Sets the data_points of this BigNumberInfo.

        :param data_points: The data_points of this BigNumberInfo.
        :type: list[BigNumberDataPoint]
        """

        self._data_points = data_points

    @property
    def big_number_items(self):
        """
        Gets the big_number_items of this BigNumberInfo.

        :return: The big_number_items of this BigNumberInfo.
        :rtype: list[BigNumberItem]
        """
        return self._big_number_items

    @big_number_items.setter
    def big_number_items(self, big_number_items):
        """
        Sets the big_number_items of this BigNumberInfo.

        :param big_number_items: The big_number_items of this BigNumberInfo.
        :type: list[BigNumberItem]
        """
        if big_number_items is None:
            raise ValueError("Invalid value for `big_number_items`, must not be `None`")

        self._big_number_items = big_number_items

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BigNumberInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
