# coding: utf-8

"""
    logicmonitor_sdk

    LogicMonitor is a cloud-based, full stack, IT infrastructure monitoring solution that allows you to manage your infrastructure from the cloud. logicmonitor_sdk lets you manage your LogicMonitor account programmatically.

    OpenAPI spec version: 1.0.0
    Contact: sdk@logicmonitor.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ConfigDiff(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'row_no': 'int',
        'type': 'str',
        'content': 'str'
    }

    attribute_map = {
        'row_no': 'rowNo',
        'type': 'type',
        'content': 'content'
    }

    def __init__(self, row_no=None, type=None, content=None):
        """
        ConfigDiff - a model defined in Swagger
        """

        self._row_no = None
        self._type = None
        self._content = None
        self.discriminator = None

        if row_no is not None:
          self.row_no = row_no
        if type is not None:
          self.type = type
        if content is not None:
          self.content = content

    @property
    def row_no(self):
        """
        Gets the row_no of this ConfigDiff.

        :return: The row_no of this ConfigDiff.
        :rtype: int
        """
        return self._row_no

    @row_no.setter
    def row_no(self, row_no):
        """
        Sets the row_no of this ConfigDiff.

        :param row_no: The row_no of this ConfigDiff.
        :type: int
        """

        self._row_no = row_no

    @property
    def type(self):
        """
        Gets the type of this ConfigDiff.

        :return: The type of this ConfigDiff.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ConfigDiff.

        :param type: The type of this ConfigDiff.
        :type: str
        """

        self._type = type

    @property
    def content(self):
        """
        Gets the content of this ConfigDiff.

        :return: The content of this ConfigDiff.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """
        Sets the content of this ConfigDiff.

        :param content: The content of this ConfigDiff.
        :type: str
        """

        self._content = content

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ConfigDiff):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
