# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RestOpsNoteDeviceGroupScope(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'full_path': 'str',
        'group_id': 'int'
    }

    attribute_map = {
        'full_path': 'fullPath',
        'group_id': 'groupId'
    }

    def __init__(self, full_path=None, group_id=None):
        """
        RestOpsNoteDeviceGroupScope - a model defined in Swagger
        """

        self._full_path = None
        self._group_id = None
        self.discriminator = None

        if full_path is not None:
          self.full_path = full_path
        if group_id is not None:
          self.group_id = group_id

    @property
    def full_path(self):
        """
        Gets the full_path of this RestOpsNoteDeviceGroupScope.

        :return: The full_path of this RestOpsNoteDeviceGroupScope.
        :rtype: str
        """
        return self._full_path

    @full_path.setter
    def full_path(self, full_path):
        """
        Sets the full_path of this RestOpsNoteDeviceGroupScope.

        :param full_path: The full_path of this RestOpsNoteDeviceGroupScope.
        :type: str
        """

        self._full_path = full_path

    @property
    def group_id(self):
        """
        Gets the group_id of this RestOpsNoteDeviceGroupScope.

        :return: The group_id of this RestOpsNoteDeviceGroupScope.
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """
        Sets the group_id of this RestOpsNoteDeviceGroupScope.

        :param group_id: The group_id of this RestOpsNoteDeviceGroupScope.
        :type: int
        """

        self._group_id = group_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RestOpsNoteDeviceGroupScope):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
