# coding: utf-8

"""
    logicmonitor_sdk

    LogicMonitor is a cloud-based, full stack, IT infrastructure monitoring solution that allows you to manage your infrastructure from the cloud. logicmonitor_sdk lets you manage your LogicMonitor account programmatically.

    OpenAPI spec version: 1.0.0
    Contact: sdk@logicmonitor.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RestBigNumberWidget(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'row_span': 'int',
        'last_updated_by': 'str',
        'big_number_info': 'BigNumberInfo',
        'user_permission': 'str',
        'col_span': 'int',
        'description': 'str',
        'type': 'str',
        'column_idx': 'int',
        'dashboard_id': 'int',
        'extra': 'str',
        'name': 'str',
        'last_updated_on': 'int',
        'theme': 'str',
        'interval': 'int',
        'id': 'int',
        'timescale': 'str',
        'order': 'int'
    }

    attribute_map = {
        'row_span': 'rowSpan',
        'last_updated_by': 'lastUpdatedBy',
        'big_number_info': 'bigNumberInfo',
        'user_permission': 'userPermission',
        'col_span': 'colSpan',
        'description': 'description',
        'type': 'type',
        'column_idx': 'columnIdx',
        'dashboard_id': 'dashboardId',
        'extra': 'extra',
        'name': 'name',
        'last_updated_on': 'lastUpdatedOn',
        'theme': 'theme',
        'interval': 'interval',
        'id': 'id',
        'timescale': 'timescale',
        'order': 'order'
    }

    def __init__(self, row_span=None, last_updated_by=None, big_number_info=None, user_permission=None, col_span=None, description=None, type=None, column_idx=None, dashboard_id=None, extra=None, name=None, last_updated_on=None, theme=None, interval=None, id=None, timescale=None, order=None):
        """
        RestBigNumberWidget - a model defined in Swagger
        """

        self._row_span = None
        self._last_updated_by = None
        self._big_number_info = None
        self._user_permission = None
        self._col_span = None
        self._description = None
        self._type = None
        self._column_idx = None
        self._dashboard_id = None
        self._extra = None
        self._name = None
        self._last_updated_on = None
        self._theme = None
        self._interval = None
        self._id = None
        self._timescale = None
        self._order = None
        self.discriminator = None

        if row_span is not None:
          self.row_span = row_span
        if last_updated_by is not None:
          self.last_updated_by = last_updated_by
        self.big_number_info = big_number_info
        if user_permission is not None:
          self.user_permission = user_permission
        if col_span is not None:
          self.col_span = col_span
        if description is not None:
          self.description = description
        self.type = type
        if column_idx is not None:
          self.column_idx = column_idx
        self.dashboard_id = dashboard_id
        if extra is not None:
          self.extra = extra
        self.name = name
        if last_updated_on is not None:
          self.last_updated_on = last_updated_on
        if theme is not None:
          self.theme = theme
        if interval is not None:
          self.interval = interval
        if id is not None:
          self.id = id
        if timescale is not None:
          self.timescale = timescale
        if order is not None:
          self.order = order

    @property
    def row_span(self):
        """
        Gets the row_span of this RestBigNumberWidget.

        :return: The row_span of this RestBigNumberWidget.
        :rtype: int
        """
        return self._row_span

    @row_span.setter
    def row_span(self, row_span):
        """
        Sets the row_span of this RestBigNumberWidget.

        :param row_span: The row_span of this RestBigNumberWidget.
        :type: int
        """

        self._row_span = row_span

    @property
    def last_updated_by(self):
        """
        Gets the last_updated_by of this RestBigNumberWidget.

        :return: The last_updated_by of this RestBigNumberWidget.
        :rtype: str
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """
        Sets the last_updated_by of this RestBigNumberWidget.

        :param last_updated_by: The last_updated_by of this RestBigNumberWidget.
        :type: str
        """

        self._last_updated_by = last_updated_by

    @property
    def big_number_info(self):
        """
        Gets the big_number_info of this RestBigNumberWidget.

        :return: The big_number_info of this RestBigNumberWidget.
        :rtype: BigNumberInfo
        """
        return self._big_number_info

    @big_number_info.setter
    def big_number_info(self, big_number_info):
        """
        Sets the big_number_info of this RestBigNumberWidget.

        :param big_number_info: The big_number_info of this RestBigNumberWidget.
        :type: BigNumberInfo
        """
        if big_number_info is None:
            raise ValueError("Invalid value for `big_number_info`, must not be `None`")

        self._big_number_info = big_number_info

    @property
    def user_permission(self):
        """
        Gets the user_permission of this RestBigNumberWidget.

        :return: The user_permission of this RestBigNumberWidget.
        :rtype: str
        """
        return self._user_permission

    @user_permission.setter
    def user_permission(self, user_permission):
        """
        Sets the user_permission of this RestBigNumberWidget.

        :param user_permission: The user_permission of this RestBigNumberWidget.
        :type: str
        """

        self._user_permission = user_permission

    @property
    def col_span(self):
        """
        Gets the col_span of this RestBigNumberWidget.

        :return: The col_span of this RestBigNumberWidget.
        :rtype: int
        """
        return self._col_span

    @col_span.setter
    def col_span(self, col_span):
        """
        Sets the col_span of this RestBigNumberWidget.

        :param col_span: The col_span of this RestBigNumberWidget.
        :type: int
        """

        self._col_span = col_span

    @property
    def description(self):
        """
        Gets the description of this RestBigNumberWidget.

        :return: The description of this RestBigNumberWidget.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this RestBigNumberWidget.

        :param description: The description of this RestBigNumberWidget.
        :type: str
        """

        self._description = description

    @property
    def type(self):
        """
        Gets the type of this RestBigNumberWidget.

        :return: The type of this RestBigNumberWidget.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this RestBigNumberWidget.

        :param type: The type of this RestBigNumberWidget.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def column_idx(self):
        """
        Gets the column_idx of this RestBigNumberWidget.

        :return: The column_idx of this RestBigNumberWidget.
        :rtype: int
        """
        return self._column_idx

    @column_idx.setter
    def column_idx(self, column_idx):
        """
        Sets the column_idx of this RestBigNumberWidget.

        :param column_idx: The column_idx of this RestBigNumberWidget.
        :type: int
        """

        self._column_idx = column_idx

    @property
    def dashboard_id(self):
        """
        Gets the dashboard_id of this RestBigNumberWidget.

        :return: The dashboard_id of this RestBigNumberWidget.
        :rtype: int
        """
        return self._dashboard_id

    @dashboard_id.setter
    def dashboard_id(self, dashboard_id):
        """
        Sets the dashboard_id of this RestBigNumberWidget.

        :param dashboard_id: The dashboard_id of this RestBigNumberWidget.
        :type: int
        """
        if dashboard_id is None:
            raise ValueError("Invalid value for `dashboard_id`, must not be `None`")

        self._dashboard_id = dashboard_id

    @property
    def extra(self):
        """
        Gets the extra of this RestBigNumberWidget.

        :return: The extra of this RestBigNumberWidget.
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """
        Sets the extra of this RestBigNumberWidget.

        :param extra: The extra of this RestBigNumberWidget.
        :type: str
        """

        self._extra = extra

    @property
    def name(self):
        """
        Gets the name of this RestBigNumberWidget.

        :return: The name of this RestBigNumberWidget.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RestBigNumberWidget.

        :param name: The name of this RestBigNumberWidget.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def last_updated_on(self):
        """
        Gets the last_updated_on of this RestBigNumberWidget.

        :return: The last_updated_on of this RestBigNumberWidget.
        :rtype: int
        """
        return self._last_updated_on

    @last_updated_on.setter
    def last_updated_on(self, last_updated_on):
        """
        Sets the last_updated_on of this RestBigNumberWidget.

        :param last_updated_on: The last_updated_on of this RestBigNumberWidget.
        :type: int
        """

        self._last_updated_on = last_updated_on

    @property
    def theme(self):
        """
        Gets the theme of this RestBigNumberWidget.

        :return: The theme of this RestBigNumberWidget.
        :rtype: str
        """
        return self._theme

    @theme.setter
    def theme(self, theme):
        """
        Sets the theme of this RestBigNumberWidget.

        :param theme: The theme of this RestBigNumberWidget.
        :type: str
        """

        self._theme = theme

    @property
    def interval(self):
        """
        Gets the interval of this RestBigNumberWidget.

        :return: The interval of this RestBigNumberWidget.
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """
        Sets the interval of this RestBigNumberWidget.

        :param interval: The interval of this RestBigNumberWidget.
        :type: int
        """

        self._interval = interval

    @property
    def id(self):
        """
        Gets the id of this RestBigNumberWidget.

        :return: The id of this RestBigNumberWidget.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this RestBigNumberWidget.

        :param id: The id of this RestBigNumberWidget.
        :type: int
        """

        self._id = id

    @property
    def timescale(self):
        """
        Gets the timescale of this RestBigNumberWidget.

        :return: The timescale of this RestBigNumberWidget.
        :rtype: str
        """
        return self._timescale

    @timescale.setter
    def timescale(self, timescale):
        """
        Sets the timescale of this RestBigNumberWidget.

        :param timescale: The timescale of this RestBigNumberWidget.
        :type: str
        """

        self._timescale = timescale

    @property
    def order(self):
        """
        Gets the order of this RestBigNumberWidget.

        :return: The order of this RestBigNumberWidget.
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """
        Sets the order of this RestBigNumberWidget.

        :param order: The order of this RestBigNumberWidget.
        :type: int
        """

        self._order = order

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RestBigNumberWidget):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
