
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-05T23:10:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6e1c3d6faa0b09716c25a3957562c1553e829d3",
 "version": "2.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
