# configuration for https://travis-ci.org
language: python

services:
  - docker
addons:
  hosts:
    - le.wtf
    - le2.wtf
    - boulder
    - boulder-mysql
    - boulder-rabbitmq
  apt:
    packages:
      # keep in sync with bootstrap.sh
      - ca-certificates
      - gcc
      - libssl-dev
      - libffi-dev
      - python
      - python-dev
      - python-virtualenv
    # python2.6 was removed from the Travis Trusty image in Jun 2017; we install
    # it ourselves.
      - python2.6
      - python2.6-dev
    # python3.5 and python3.6 are not pre-installed on Travis,
    # https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
    #
    # We do this instead of setting travis's python: option, because for some
    # odd reason, that gives us errors about missing docker-compose:
    # https://travis-ci.org/zenhack/simp_le/jobs/187594794#L218
      - python3.5
      - python3.6
      - python3.6-dev
    sources:
      - deadsnakes

env:
  # delegate tests to tox; build matrix contains one suite per testenv
  matrix:
    - TOXENV=lint
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=py26-oldest
    - TOXENV=py27-oldest
    - TOXENV=py33-oldest
    - TOXENV=py34-oldest
    - TOXENV=py35-oldest
    - TOXENV=py36-oldest

before_install: ./tests/travis.sh before_install
install: ./tests/travis.sh install
script: ./tests/travis.sh script

notifications:
  irc:
    channels:
      - "irc.freenode.org#simp_le"
    use_notice: true
    skip_join: true
