version: "2"

services:
  periodic:
    build: .
    entrypoint: ["/tmp/wait-for.sh", "server:80", "--", "python", "-m", "periodic"]
    volumes:
      - ./tle-storage-service.yaml:/opt/tle-storage-service/config/tle-storage-service.yaml:ro
      - ./wait-for.sh:/tmp/wait-for.sh:ro
    links:
      - db
      - server
  server:
    build: .
    entrypoint: ["/tmp/wait-for.sh", "db:5432", "--", "python", "-m", "server"]
    volumes:
      - ./tle-storage-service.yaml:/opt/tle-storage-service/config/tle-storage-service.yaml:ro
      - ./wait-for.sh:/tmp/wait-for.sh:ro
    links:
      - db
    ports:
      - 8080:80
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=tle_user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=tle