from ...tl.mtproto_request import MTProtoRequest


class InputMessagesFilterEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. TL definition below.
    inputMessagesFilterEmpty#57e2f66c  = MessagesFilter"""

    # Telegram's constructor (U)ID for this class
    constructor_id = 0x57e2f66c
    # Also the ID of its resulting type for fast checks
    subclass_of_id = 0x8a36ec14

    def __init__(self):
        super().__init__()

    @staticmethod
    def to_dict():
        return {}

    def on_send(self, writer):
        writer.write_int(InputMessagesFilterEmpty.constructor_id, signed=False)

    @staticmethod
    def empty():
        """Returns an "empty" instance (attributes=None)"""
        return InputMessagesFilterEmpty()

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMessagesFilterEmpty#57e2f66c  = MessagesFilter'

    def __str__(self):
        return '(inputMessagesFilterEmpty (ID: 0x57e2f66c) = ())'.format()
