
# This file is automatically generated from sisl setup.py
major   = 0
minor   = 8
micro   = 5
version = '.'.join(map(str,[major, minor, micro]))
release = version
# Git information
git_revision = '8f526d65c4c8e6df2cc59ea84ef2938cbcd2e10b'
git_revision_short = git_revision[:7]

if not release:
    version = version + '-' + git_revision
