# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='use_recaptcha',
            field=models.BooleanField(default=False),
        ),
    ]
