batchsize: 128
valid_batchsize: 128
valid_trigger: [1, 'epoch']
snapshot_trigger: [20, 'epoch']
log_trigger: [1, "epoch"]
stop_epoch: 20
seed: 0

dataset:
  train:
    file: dataset.py
    name: Dataset
    args:
      split: train
  valid:
    file: dataset.py
    name: Dataset
    args:
      split: valid

model:
  file: model.py
  name: Model
  args:
    n_class: 10

loss:
  file: loss.py
  name: Loss

optimizer:
  method: MomentumSGD
  args:
    lr: 0.01
  weight_decay: 0.0001
  lr_drop_ratio: 0.1
  lr_drop_triggers:
    points: [10, 15]
    unit: epoch

trainer_extension:
  - dump_graph:
      root_name: main/loss
      out_name: cg.dot
  - PlotReport:
      y_keys:
        - main/loss
        - validation/main/loss
      x_key: epoch
      file_name: loss.png
  - PlotReport:
      y_keys:
        - main/accuracy
        - validation/main/accuracy
      x_key: epoch
      file_name: accuracy.png
  - PrintReport:
    - epoch
    - iteration
    - main/loss
    - validation/main/loss
    - main/accuracy
    - validation/main/accuracy
    - elapsed_time
    - lr
  - ProgressBar
