dist: trusty
sudo: required

before_install:
  - sudo service postgresql stop
  - sudo apt-get install python-pip postgresql collectd
  # Remove Travis own Python version otherwise it gets loaded by collectd
  # Python plugin, and it fails because the ABI is different.
  - sudo rm -rf /opt/python
  - sudo pip install -U pip
install:
  - sudo pip install -U gnocchi[postgresql,file] pifpaf[gnocchi] $TRAVIS_BUILD_DIR
script:
  - $TRAVIS_BUILD_DIR/run-tests.sh

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gnocchi"
