# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 12:27
from __future__ import unicode_literals

import cms.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djangocms_text_ckeditor.fields
import filer.fields.image
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('pcart_people', '0003_auto_20170723_1939'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, verbose_name='Tags')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pcart_people.Person', verbose_name='Author')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleBlockPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pcart_newsblog_articleblockpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('template_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Template name')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcart_newsblog.Article', verbose_name='Article')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('lead_in', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='The lead gives the reader the main idea of the story, this is useful in overviews, lists or as an introduction to your article.', verbose_name='Lead')),
                ('page_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Page title')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Meta keywords')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pcart_newsblog.Article')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Article Translation',
                'db_table': 'pcart_newsblog_article_translation',
                'managed': True,
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Position')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pcart_newsblog.Category')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Category Translation',
                'db_table': 'pcart_newsblog_category_translation',
                'managed': True,
                'db_tablespace': '',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pcart_newsblog.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_article_content', slotname='newsblog_article_content', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Optional. Please supply a photo of this person.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image', verbose_name='Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
