- name: install necessary RPM files
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python-paramiko
    - nss
    - iptables
    - iptables-services
    - "{{ jenkins_rpm }}"
    - graphviz
    - lftp
    - gcc
    - libffi-devel
    - python-devel
    - openssl-devel
    - libxml2-devel
    - libxslt-devel
    - krb5-workstation
    - python-futures
    - python-six
    - python-unittest2
    - python-configobj
    - python-nose
    - cloud-utils
    - python-glanceclient
    - python-keystoneclient
    - python-novaclient
    - python-neutronclient
    - wget
    - "{{ python_pip_package }}"
    - python-virtualenv
    - initscripts
    - cloud-utils

- name: install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

- name: install gcc_compat where necessary
  package:
    name: "{{ gcc_compat_package }}"
    state: present
  when: gcc_compat_package is defined

# This blacklist must be done *after* the package installation defined above,
# otherwise packages can be blacklisted before they are installed initially.
- name: pin certain packages
  lineinfile:
    dest: "{{ version_pin_file }}"
    line: "exclude={{ upgrade_blacklist | join(' ') }}"
    state: present
    regexp: "^exclude=.*$"
