# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['position'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
