language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3.5-5.8.0
install:
    - pip install -U pip setuptools
    - pip install -U coveralls coverage
    - pip install -U -e .[test,docs]
script:
    - coverage run setup.py test -q
    - coverage run -a -m sphinx -b doctest -d docs/_build/doctrees docs docs/_build/doctest
after_success:
    - coveralls
notifications:
    email: false
cache: pip
