__version__ = "0.1.8"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.1.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '413c87defb9f90a215657d60981f2a00be550723'
__git_head_subject__ = u'Finished Release v0.1.8'
__git_head_message__ = u''
__git_dirty_diff__ = u''