
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-22T05:03:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b38e58b0a800190bbb41291ccb8bb8a156695c5e",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
