# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dform', '0005_answergroup_ip_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='use_recaptcha',
        ),
    ]
