# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.9.2.dev2'
VERSION = '0.9.2.dev2'
FULL_VERSION = '0.9.2.dev2'
GIT_REVISION = '90ac0acd6e634fcba7ed816a9912199a272aed52'
GIT_VERSION = '0.9.2.dev2+90ac0ac'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
