# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topiceval.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1357, 744)
        self.radioButton_1 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_1.setGeometry(QtCore.QRect(360, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_1.setObjectName("radioButton_1")
        self.buttonGroup_1 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_1.setObjectName("buttonGroup_1")
        self.buttonGroup_1.addButton(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(420, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_1.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(480, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_1.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(540, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup_1.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setGeometry(QtCore.QRect(600, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_1.addButton(self.radioButton_5)
        self.instructionsTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.instructionsTextBrowser.setGeometry(QtCore.QRect(20, 30, 271, 601))
        self.instructionsTextBrowser.setAutoFillBackground(False)
        self.instructionsTextBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.instructionsTextBrowser.setObjectName("instructionsTextBrowser")
        self.scoreLabel_1 = QtWidgets.QLabel(Dialog)
        self.scoreLabel_1.setGeometry(QtCore.QRect(470, 640, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scoreLabel_1.setFont(font)
        self.scoreLabel_1.setStyleSheet("color:rgb(255, 255, 255)")
        self.scoreLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreLabel_1.setObjectName("scoreLabel_1")
        self.bkdLabel = QtWidgets.QLabel(Dialog)
        self.bkdLabel.setGeometry(QtCore.QRect(0, 0, 1361, 751))
        self.bkdLabel.setText("")
        self.bkdLabel.setObjectName("bkdLabel")
        self.verticalSepLine = QtWidgets.QFrame(Dialog)
        self.verticalSepLine.setGeometry(QtCore.QRect(300, 0, 20, 751))
        self.verticalSepLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.verticalSepLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalSepLine.setObjectName("verticalSepLine")
        self.listWidget_1 = QtWidgets.QListWidget(Dialog)
        self.listWidget_1.setGeometry(QtCore.QRect(355, 30, 281, 600))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_1.setFont(font)
        self.listWidget_1.setAutoFillBackground(True)
        self.listWidget_1.setStyleSheet("color:rgb(85, 170, 255); border-bottom: 1px solid black")
        self.listWidget_1.setAlternatingRowColors(True)
        self.listWidget_1.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_1.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_1.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_1.setUniformItemSizes(False)
        self.listWidget_1.setBatchSize(10)
        self.listWidget_1.setWordWrap(False)
        self.listWidget_1.setObjectName("listWidget_1")
        self.showNext10PushButton_1 = QtWidgets.QPushButton(Dialog)
        self.showNext10PushButton_1.setGeometry(QtCore.QRect(524, 590, 101, 23))
        self.showNext10PushButton_1.setObjectName("showNext10PushButton_1")
        self.showPrevious10PushButton_1 = QtWidgets.QPushButton(Dialog)
        self.showPrevious10PushButton_1.setGeometry(QtCore.QRect(370, 590, 101, 23))
        self.showPrevious10PushButton_1.setObjectName("showPrevious10PushButton_1")
        self.scoreLabel_2 = QtWidgets.QLabel(Dialog)
        self.scoreLabel_2.setGeometry(QtCore.QRect(810, 640, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scoreLabel_2.setFont(font)
        self.scoreLabel_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.scoreLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreLabel_2.setObjectName("scoreLabel_2")
        self.radioButton_6 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_6.setGeometry(QtCore.QRect(880, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_7.setGeometry(QtCore.QRect(700, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_2.addButton(self.radioButton_7)
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(695, 30, 281, 600))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setAutoFillBackground(True)
        self.listWidget_2.setStyleSheet("color:rgb(85, 170, 255); border-bottom: 1px solid black")
        self.listWidget_2.setAlternatingRowColors(True)
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_2.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_2.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_2.setUniformItemSizes(False)
        self.listWidget_2.setBatchSize(10)
        self.listWidget_2.setWordWrap(False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.radioButton_8 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_8.setGeometry(QtCore.QRect(940, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_2.addButton(self.radioButton_8)
        self.nextCommandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.nextCommandLinkButton.setGeometry(QtCore.QRect(800, 700, 91, 41))
        self.nextCommandLinkButton.setStyleSheet("color:rgb(255, 255, 255)")
        self.nextCommandLinkButton.setObjectName("nextCommandLinkButton")
        self.radioButton_9 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_9.setGeometry(QtCore.QRect(820, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_2.addButton(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_10.setGeometry(QtCore.QRect(760, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup_2.addButton(self.radioButton_10)
        self.showNext10PushButton_2 = QtWidgets.QPushButton(Dialog)
        self.showNext10PushButton_2.setGeometry(QtCore.QRect(864, 590, 101, 23))
        self.showNext10PushButton_2.setObjectName("showNext10PushButton_2")
        self.showPrevious10PushButton_2 = QtWidgets.QPushButton(Dialog)
        self.showPrevious10PushButton_2.setGeometry(QtCore.QRect(710, 590, 101, 23))
        self.showPrevious10PushButton_2.setObjectName("showPrevious10PushButton_2")
        self.radioButton_11 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_11.setGeometry(QtCore.QRect(1280, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_11)
        self.showNext10PushButton_3 = QtWidgets.QPushButton(Dialog)
        self.showNext10PushButton_3.setGeometry(QtCore.QRect(1204, 590, 101, 23))
        self.showNext10PushButton_3.setObjectName("showNext10PushButton_3")
        self.showPrevious10PushButton_3 = QtWidgets.QPushButton(Dialog)
        self.showPrevious10PushButton_3.setGeometry(QtCore.QRect(1050, 590, 101, 23))
        self.showPrevious10PushButton_3.setObjectName("showPrevious10PushButton_3")
        self.scoreLabel_3 = QtWidgets.QLabel(Dialog)
        self.scoreLabel_3.setGeometry(QtCore.QRect(1150, 640, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scoreLabel_3.setFont(font)
        self.scoreLabel_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.scoreLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreLabel_3.setObjectName("scoreLabel_3")
        self.listWidget_3 = QtWidgets.QListWidget(Dialog)
        self.listWidget_3.setGeometry(QtCore.QRect(1035, 30, 281, 600))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setAutoFillBackground(True)
        self.listWidget_3.setStyleSheet("color:rgb(85, 170, 255); border-bottom: 1px solid black")
        self.listWidget_3.setAlternatingRowColors(True)
        self.listWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_3.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_3.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_3.setUniformItemSizes(False)
        self.listWidget_3.setBatchSize(10)
        self.listWidget_3.setWordWrap(False)
        self.listWidget_3.setObjectName("listWidget_3")
        self.radioButton_12 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_12.setGeometry(QtCore.QRect(1160, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_12.setObjectName("radioButton_12")
        self.buttonGroup_3.addButton(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_13.setGeometry(QtCore.QRect(1040, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_13.setObjectName("radioButton_13")
        self.buttonGroup_3.addButton(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_14.setGeometry(QtCore.QRect(1220, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_14.setObjectName("radioButton_14")
        self.buttonGroup_3.addButton(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_15.setGeometry(QtCore.QRect(1100, 670, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setStyleSheet("color:rgb(255, 255, 255)")
        self.radioButton_15.setObjectName("radioButton_15")
        self.buttonGroup_3.addButton(self.radioButton_15)
        self.bkdLabel.raise_()
        self.radioButton_1.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.instructionsTextBrowser.raise_()
        self.scoreLabel_1.raise_()
        self.verticalSepLine.raise_()
        self.listWidget_1.raise_()
        self.showNext10PushButton_1.raise_()
        self.showPrevious10PushButton_1.raise_()
        self.scoreLabel_2.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.listWidget_2.raise_()
        self.radioButton_8.raise_()
        self.nextCommandLinkButton.raise_()
        self.radioButton_9.raise_()
        self.radioButton_10.raise_()
        self.showNext10PushButton_2.raise_()
        self.showPrevious10PushButton_2.raise_()
        self.radioButton_11.raise_()
        self.scoreLabel_3.raise_()
        self.listWidget_3.raise_()
        self.radioButton_12.raise_()
        self.radioButton_13.raise_()
        self.radioButton_14.raise_()
        self.radioButton_15.raise_()
        self.showNext10PushButton_3.raise_()
        self.showPrevious10PushButton_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Topic Model Evaluation"))
        self.radioButton_1.setText(_translate("Dialog", "1"))
        self.radioButton_2.setText(_translate("Dialog", "2"))
        self.radioButton_3.setText(_translate("Dialog", "3"))
        self.radioButton_4.setText(_translate("Dialog", "4"))
        self.radioButton_5.setText(_translate("Dialog", "5"))
        self.instructionsTextBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Instructions</span><span style=\" font-size:12pt;\">:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. The words represent top 10 words from one of the topics inferred from your emails, the top word is highest weighted and bottom word the lowest among the top 10.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. Please select a score on a range of </span><span style=\" font-size:12pt; font-weight:600;\">1 (bad) to 5 (great)</span><span style=\" font-size:12pt;\"> based on the  critirea mentioned below</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. You have to judge each topic based on:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- Interpretability and Meaningfulness</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- Ease with which you can provide a representative label to the topic</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- Its merit in revealing a significant/interesting topic/theme in your mails</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- It is not too broad or too narrow in defining a theme. A broad topic would have multiple themes fused, and a narrow one would be too restricted and specific, applying to only ~ &lt;5 of your mails. </span></p></body></html>"))
        self.scoreLabel_1.setText(_translate("Dialog", "Score"))
        self.showNext10PushButton_1.setText(_translate("Dialog", "Show Next 10"))
        self.showPrevious10PushButton_1.setText(_translate("Dialog", "Show Previous 10"))
        self.scoreLabel_2.setText(_translate("Dialog", "Score"))
        self.radioButton_6.setText(_translate("Dialog", "4"))
        self.radioButton_7.setText(_translate("Dialog", "1"))
        self.radioButton_8.setText(_translate("Dialog", "5"))
        self.nextCommandLinkButton.setText(_translate("Dialog", "Next"))
        self.radioButton_9.setText(_translate("Dialog", "3"))
        self.radioButton_10.setText(_translate("Dialog", "2"))
        self.showNext10PushButton_2.setText(_translate("Dialog", "Show Next 10"))
        self.showPrevious10PushButton_2.setText(_translate("Dialog", "Show Previous 10"))
        self.radioButton_11.setText(_translate("Dialog", "5"))
        self.showNext10PushButton_3.setText(_translate("Dialog", "Show Next 10"))
        self.showPrevious10PushButton_3.setText(_translate("Dialog", "Show Previous 10"))
        self.scoreLabel_3.setText(_translate("Dialog", "Score"))
        self.radioButton_12.setText(_translate("Dialog", "3"))
        self.radioButton_13.setText(_translate("Dialog", "1"))
        self.radioButton_14.setText(_translate("Dialog", "4"))
        self.radioButton_15.setText(_translate("Dialog", "2"))

