---

# Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.4

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out:
#   http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
##services:
##  - mysql:latest
##  - postgres:latest

# Environment
variables:
  HYPERSHOT_DEBUG: "1"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
##cache:
##  paths:
##    - ~/.cache/pip/

# Install dependencies etc.
before_script:
  - python -V  # Print out python version for debugging

# Jobs
tox:
  stage: test
  script:
    - python3 setup.py --version
    - pip install -r requirements-dev.txt
    - tox -e lint -- --reports=y
    - tox -e py34
    - hypershot --config-dir=docs/examples templates
  artifacts:
    paths:
      - build/cov_html
    expire_in: 3 days

docs:
  # Run this in 'deploy', so Sphinx errors do not prevent
  # publishing of coverage reports
  stage: deploy
  script:
    - pip install tox
    - tox -e docs

pages:
  stage: deploy
  dependencies:
    - tox
  script:
    - mv build/cov_html/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

...
