__version__ = "0.2.3"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.2.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '30f82b8ee896f5ea8b5e1b8d21490490c89c48ac'
__git_head_subject__ = u'Finished Release v0.2.3'
__git_head_message__ = u''
__git_dirty_diff__ = u''