
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-07-06T12:55:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "623c73407cfc3320e6103164e8cf8dff2b6c0410",
 "version": "1.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
